  
version: '3.7'

networks:
  localdev:
    external: true
    name: localdev

services:
  hugopage:
    image: klakegg/hugo:ext-ubuntu
    container_name: hugo
    networks:
      - localdev
    restart: on-failure
    volumes:
      - ./archetypes:/src/archetypes
      - ./content:/src/content
      - ./data:/src/data
      - ./layouts:/src/layouts
      - ./static:/src/static
      - ./task0_module1/dist:/src/dist
      - ./themes:/src/themes
      - ./config.toml:/src/config.toml
    command: server -D
    ports:
      - 1313:1313
    environment:
      - HUGO_DESTINATION=dist
      - HUGO_ENV=DEV
