#!/bin/bash
mkdir ./dist
touch ./.gitignore
touch ./dist/master.zip
echo "~/validation/module1_task0/dist" >> ./.gitignore
echo "hugoblog" >> ./.gitignore
cd ./dist
#
wget https://github.com/theNewDynamic/gohugo-theme-ananke/archive/master.zip
hugo new site "Awesome Inc."
git init
mkdir ./"Awesome Inc."/themes -p
unzip master.zip -d ./"Awesome Inc."/themes
mv ./"Awesome Inc."/themes/gohugo-theme-ananke-master ./"Awesome Inc."/themes/ananke
cd ./"Awesome Inc."
#
echo theme = \"ananke\" >> config.toml
hugo new posts/welcome.md
echo  "Welcome to Awesome Inc." >> ./content/posts/welcome.md
#
git add .
git commit -m "Awesome Inc. blog made with Hugo"
git push origin
#
